/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LocationImport } from './routes/location'
import { Route as ClipboardImport } from './routes/clipboard'
import { Route as IndexImport } from './routes/index'
import { Route as ResourceIdImport } from './routes/resource.$id'

// Create/Update Routes

const LocationRoute = LocationImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRoute,
} as any)

const ClipboardRoute = ClipboardImport.update({
  id: '/clipboard',
  path: '/clipboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResourceIdRoute = ResourceIdImport.update({
  id: '/resource/$id',
  path: '/resource/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/clipboard': {
      id: '/clipboard'
      path: '/clipboard'
      fullPath: '/clipboard'
      preLoaderRoute: typeof ClipboardImport
      parentRoute: typeof rootRoute
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationImport
      parentRoute: typeof rootRoute
    }
    '/resource/$id': {
      id: '/resource/$id'
      path: '/resource/$id'
      fullPath: '/resource/$id'
      preLoaderRoute: typeof ResourceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clipboard': typeof ClipboardRoute
  '/location': typeof LocationRoute
  '/resource/$id': typeof ResourceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clipboard': typeof ClipboardRoute
  '/location': typeof LocationRoute
  '/resource/$id': typeof ResourceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/clipboard': typeof ClipboardRoute
  '/location': typeof LocationRoute
  '/resource/$id': typeof ResourceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clipboard' | '/location' | '/resource/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clipboard' | '/location' | '/resource/$id'
  id: '__root__' | '/' | '/clipboard' | '/location' | '/resource/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClipboardRoute: typeof ClipboardRoute
  LocationRoute: typeof LocationRoute
  ResourceIdRoute: typeof ResourceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipboardRoute: ClipboardRoute,
  LocationRoute: LocationRoute,
  ResourceIdRoute: ResourceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/clipboard",
        "/location",
        "/resource/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/clipboard": {
      "filePath": "clipboard.tsx"
    },
    "/location": {
      "filePath": "location.tsx"
    },
    "/resource/$id": {
      "filePath": "resource.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
