table clipboard_services {
  session_id text [not null]
  service_id text [not null]

  indexes {
    (session_id, service_id) [pk]
  }
}

table sessions {
  id text [pk, not null]
  lat real [not null]
  lng real [not null]
  address text [not null]
}

ref: clipboard_services.session_id > sessions.id